# Generated by Django 5.2.4 on 2025-07-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_lesson_lessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='Instructor', max_length=100),
        ),
    ]
