# Generated by Django 5.2.4 on 2025-07-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_post_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
