# Generated by Django 5.2.5 on 2025-11-24 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_course_duration_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complete_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='progress_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_level_xp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='catalog.category'),
        ),
    ]
