# Generated by Django 5.2.5 on 2025-11-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_question_correct_option_question_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='total_marks',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
