# Generated by Django 5.2.5 on 2025-11-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_quizresult_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=4.8),
        ),
    ]
