# Generated by Django 5.2.5 on 2025-11-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_course_price_course_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('4 weeks', '4 weeks'), ('8 weeks', '8 weeks'), ('12 weeks', '12 weeks'), ('16 weeks', '16 weeks'), ('20 weeks', '20 weeks')], default='4 weeks', max_length=20),
        ),
    ]
